name: Build & Tests App

on:
  workflow_dispatch:
    inputs:
      run_publish:
        description: "Publish App"
        required: false
        type: boolean
        default: false
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
env:
   NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Set up .NET Core SDK
      - name: Set up .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.x'
      
      # Cache NuGet packages
      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      
      # Restore NuGet packages
      - name: Restore NuGet packages
        run: dotnet restore
      
      # Build the solution
      - name: Build the solution
        run: dotnet build --configuration Release
        
      # Run tests with code coverage collection
      - name: Run Tests with Code Coverage
        run: dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage"
        
      # Generate code coverage report in Cobertura format
      - name: Generate Code Coverage Report
        run: |
          dotnet tool install -g dotnet-reportgenerator-globaltool
          reportgenerator "-reports:Tests/**/coverage.cobertura.xml" "-targetdir:coverage" -reporttypes:Cobertura  

      # Upload test results and coverage reports as artifacts
      - name: Upload Code Coverage Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: 'coverage/Cobertura.xml'  # Adjust path if necessary 
          
      # Publish the build artifacts (optional)
      - name: Publish App Artifacts
        id: publish_app  # Assign an ID to reference later
        if: github.ref_name == 'develop' || github.ref_name == 'master' || github.event.inputs.run_publish == 'true'
        run: dotnet publish --configuration Release --output ../publish

      # Upload build artifacts (conditional on the success of the publish app step)
      - name: Upload App Artifacts
        if: steps.publish_app.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: PublishedBuild
          path: ./publish
  
  upload_tests_coverage:
    runs-on: windows-latest
    needs: build
    environment: AppConfig
    steps:
      # Download the coverage report artifact
      - name: Download Code Coverage Artifacts
        uses: actions/download-artifact@v4
        with:
          name: code-coverage-report
          path: coverage
        
      # Upload code coverage to Codecov
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/Cobertura.xml
          fail_ci_if_error: true
          verbose: true