name: Build & Tests App

on:
  workflow_dispatch:
    inputs:
      run_publish:
        description: "Run publish"
        required: false
        type: boolean
        default: false
      architecture:
        description: "architecture"
        required: false
        default: "win-x64"
        type: choice
        options:
          - win-x64
          - win-arm64  
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
env:
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Set up .NET Core SDK
      - name: Set up .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.x'  # Adjust to your .NET version
      
      # Cache NuGet packages
      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      
      # Restore NuGet packages
      - name: Restore NuGet packages
        run: dotnet restore
      
      # Build the solution
      - name: Build the solution
        run: dotnet build --configuration Release
  tests_coverage:
    runs-on: windows-latest
    needs: build
    environment: AppConfig
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Run tests with code coverage collection
      - name: Run Tests with Code Coverage
        run: dotnet test Browser.Wpf.sln --configuration Release --collect:"XPlat Code Coverage"
      
      # Generate code coverage report in Cobertura format
      - name: Generate Code Coverage Report
        run: |
          dotnet tool install -g dotnet-reportgenerator-globaltool
          reportgenerator "-reports:Tests/**/coverage.cobertura.xml" "-targetdir:coverage" -reporttypes:Cobertura
      
      # Upload code coverage to Codecov
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/Cobertura.xml
          fail_ci_if_error: true
          verbose: true

  publish:
    runs-on: windows-latest
    needs: build
    if: github.ref_name == 'develop' || github.ref_name == 'master' || github.event.inputs.run_publish == 'true'
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Publish the build artifacts
      - name: Publish Build Artifacts
        run:  dotnet publish Src\Browser.App.Wpf\Browser.App.Wpf.csproj --configuration Release --framework net6.0-windows --output publish --runtime ${{ inputs.architecture }} --self-contained false -p:PublishReadyToRun=true -p:IncludeNativeLibrariesForSelfExtract=true -p:IncludeAllContentForSelfExtract=true -p:PublishSingleFile=true -p:UseAppHost=true
      
      # Upload build artifacts (optional)
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BrowserApp-${{ inputs.architecture }}-${{ github.run_number }}  # Include run number
          path: ./publish
