name: Build WPF Application

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up .NET Core SDK
    - name: Set up .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.x' # Adjust to your .NET version

    # Change working directory to 'Src' and restore NuGet packages
    - name: Restore NuGet packages
      run: dotnet restore
      working-directory: Src

    # Build the project in 'Src' directory
    - name: Build the solution
      run: dotnet build --configuration Release
      working-directory: Src

    # Optional: Run tests in 'Src'
    - name: Run Tests
      run: dotnet test --no-build --verbosity normal --configuration Release
      working-directory: Src

    # Publish the build artifacts from 'Src'
    - name: Publish Build Artifacts
      run: dotnet publish --configuration Release --output ../publish
      working-directory: Src

    # Upload artifacts (optional)
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: PublishedBuild
        path: ./publish
